dynamic_smt:
  threshold: 40.0

hugepage:
  l1_miss_threshold: 5.0
  l2_miss_threshold: 10.0

numa_analysis:
  thread_threshold: 200  # thread count threshold to use numa native schedule.

smc_d_analysis:
  change_rate: 0.1
  lo_net_flow: 100 # MB/S