dynamic_smt:
  threshold: 40.0

hugepage:
  l1_miss_threshold: 5.0
  l2_miss_threshold: 10.0

numa_analysis:
  thread_threshold: 200  # thread count threshold to use numa native schedule.

smc_d_analysis:
  change_rate: 0.1
  lo_net_flow: 100 # MB/S

docker_coordination_burst:
  host_cpu_usage_threshold: 45
  docker_cpu_usage_threshold: 95

microarch_tidnocmp:
  service_list:
    - mysqld # Supported service. The default value is mysqld.
  cpu_part:
    - 0xd02
xcall_analysis:
  threshold: 5 # Kernel cpu usage
  num: 5 # top num syscall